### ISSUE TITLE
Stringify a Date as number instead of string.

### ISSUE THREAD

**Issue by delvedor** [mcollina/fast-json-stringify#9]
I did this bench, and the result is remarkable.
```javascript
'use strict'

const benchmark = require('benchmark')
const suite = new benchmark.Suite()
const date = new Date()

suite
  .add('toISOString()', function () {
    date.toISOString()
  })
  .add('getTime()', function () {
    date.getTime()
  })
  .on('cycle', function (event) {
    console.log(String(event.target))
  })
  .on('complete', function () {})
  .run()
```
Result:
```bash
toISOString() x 2,132,610 ops/sec ±0.84% (91 runs sampled)
getTime() x 86,037,830 ops/sec ±0.96% (92 runs sampled)
```
Should we move from `.toISOString()` to `.getTime()`?

**Comment by mcollina** [comment]
No, that would be a violation of the JSON specification. We represent dates as string. Converting them to integers in the schema would be up to the user.

We should document all of this in the README.

BTW, this is why we use `Date.now()` in pino: https://github.com/mcollina/pino/pull/5.
